# Generated by Django 4.2.29 on 2026-04-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('pro', 'Pro')], default='beginner', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='has_completed_placement',
            field=models.BooleanField(default=False),
        ),
    ]
