# Generated by Django 4.2.29 on 2026-03-13 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('passage_text', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_passages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reading_passages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict, help_text='Map of question_id to user answer')),
                ('score', models.FloatField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent in seconds')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='reading.readingpassage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reading_tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false_ng', 'True/False/Not Given'), ('fill_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('short_answer', 'Short Answer')], max_length=15)),
                ('options', models.JSONField(blank=True, help_text='Options for MCQ/Matching as JSON array', null=True)),
                ('correct_answer', models.CharField(max_length=500)),
                ('explanation', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reading.readingpassage')),
            ],
            options={
                'db_table': 'reading_questions',
                'ordering': ['order'],
            },
        ),
    ]
