# Generated by Django 4.2.29 on 2026-03-13 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('part_number', models.IntegerField(choices=[(1, 'Part 1 - Introduction'), (2, 'Part 2 - Long Turn'), (3, 'Part 3 - Discussion')], default=1)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('evaluated', 'Evaluated')], default='in_progress', max_length=15)),
                ('transcript', models.TextField(blank=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'speaking_tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronunciation_score', models.FloatField(default=0)),
                ('fluency_score', models.FloatField(default=0)),
                ('grammar_score', models.FloatField(default=0)),
                ('coherence_score', models.FloatField(default=0)),
                ('vocabulary_score', models.FloatField(default=0)),
                ('overall_band', models.FloatField(default=0)),
                ('feedback_text', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('ai_model_used', models.CharField(default='gemini-flash', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('speaking_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='speaking.speakingtest')),
            ],
            options={
                'db_table': 'speaking_feedback',
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audio/')),
                ('duration', models.FloatField(default=0)),
                ('format', models.CharField(default='webm', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('speaking_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='speaking.speakingtest')),
            ],
            options={
                'db_table': 'audio_files',
            },
        ),
    ]
