# Generated by Django 4.2.29 on 2026-04-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0002_speakingtest_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingtest',
            name='set_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Groups Part 1/2/3 of the same admin-created test set', null=True),
        ),
        migrations.AddField(
            model_name='speakingtest',
            name='theme',
            field=models.CharField(blank=True, help_text='Shared theme across the 3 parts of a test set', max_length=200),
        ),
    ]
