# Generated by Django 4.2.29 on 2026-04-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0003_speakingtest_set_id_speakingtest_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingtest',
            name='session_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Groups the 3 parts of a single student attempt', null=True),
        ),
    ]
