# Generated by Django 4.2.29 on 2026-03-13 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('task1', 'Task 1'), ('task2', 'Task 2')], max_length=5)),
                ('topic', models.TextField()),
                ('instructions', models.TextField(blank=True)),
                ('writing_text', models.TextField(blank=True)),
                ('word_count', models.IntegerField(default=0)),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent in seconds')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('evaluated', 'Evaluated')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'writing_tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_achievement', models.FloatField(default=0)),
                ('coherence_cohesion', models.FloatField(default=0)),
                ('lexical_resource', models.FloatField(default=0)),
                ('grammatical_range', models.FloatField(default=0)),
                ('overall_band', models.FloatField(default=0)),
                ('feedback_text', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('ai_model_used', models.CharField(default='gemini-flash', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('writing_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='writing.writingtest')),
            ],
            options={
                'db_table': 'writing_feedback',
            },
        ),
    ]
